site_name: k8s study
site_url: https://mkbooks.github.io/k8s-mengfanjie/

theme:
  name: material

# Page tree
nav:
  - 0-开营直播: 0/0.0.md
  - 1-Go 语言基础:
    - 1.1Go 语言特性:
      - 1.1.1Go 语言特性·第一课:
        - 变量: 1/1.1/1.1.1/1.1.1.1.md
        - 数组: 1/1.1/1.1.1/1.1.1.2.md
